# Generated by Django 4.2.6 on 2023-10-17 12:10

from django.db import migrations

import choices_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_status",
            field=choices_fields.fields.IntegerChoicesArrayField(
                blank=True, choices=[(1, "One"), (2, "Two"), (3, "Three")], default=list
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=choices_fields.fields.TextChoicesArrayField(
                blank=True,
                choices=[
                    ("owner", "Account owner"),
                    ("admin", "Administrator"),
                    ("user", "User"),
                ],
                default=list,
            ),
        ),
    ]
